name: Auto-generate Icon Gallery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run gallery generator
        run: python generate_index.py

      - name: Commit and push if index.md changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.md
          git diff --cached --quiet || git commit -m "🤖 Update gallery index.html"
          git push
